name: leafresh
description: "Leafresh Flutter Service"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5 # provider 패키지 추가
  http: ^0.13.4    # http 패키지 추가

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
